add globalStyles and change files
deki84/capstone-project pull request #8
Opened 2022-09-20 09:24 UTC by deki84

2022-09-20 11:59 UTC, ben-me requested changes
Please add a text description with what you have done, how and why. Right now there  is no info text in the pull request.

2022-09-20 11:59 UTC, ben-me commented on pages/_app.js
> +  return (
You seem to have a double return here. The code will stop after the first return and not continue to the second one.

2022-09-20 12:01 UTC, ben-me commented on components/GlobalStlyle.js
> +export default GlobalStyle;
You already export the constant GlobalStyle in line 3. The default export in line 13 is redundant. You can remove one of them.

2022-09-20 12:05 UTC, ben-me commented on pages/index.js
> +const headline = styled.h1`
I'm not 100% sure on this but I think it's best to start the name of a styled component with an uppercase letter.
So Headline instead of headline.

2022-09-20 14:01 UTC, ben-me commented on babelrc
> +{
File name has to be .babelrc

2022-09-21 07:12 UTC, AnH13-6 approved these changes

2022-09-21 09:14 UTC, merged